manifest:
  defaults:
    remote: github/manojkumarpaladugu

  remotes:
    - name: github/manojkumarpaladugu
      url-base: ssh://git@github.com/manojkumarpaladugu

  projects:
    - name: zephyr
      remote: github/manojkumarpaladugu
      repo-path: zephyr
      revision: v3.7.1
      path: zephyr
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)
    - name: zephyr-plus
      remote: github/manojkumarpaladugu
      repo-path: zephyr-plus
      revision: main
      path: modules/zephyr-plus
    - name: Commons
      remote: github/manojkumarpaladugu
      repo-path: Commons
      revision: main
      path: modules/lib/Commons
